'use client';
import {createContext,useContext,useEffect,useState,ReactNode} from 'react';
import {MessageCircle,Phone} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {LineSettings,lineLink,LINE_OA_URL,CONTACT_PHONE} from '@/lib/line';
import {Service,money} from '@/lib/catalog';
import {Departure,dateText,serviceCode,departureExpired,tourClosed} from '@/lib/tour';
const LineContext=createContext<LineSettings>({lineId:'',lineUrl:LINE_OA_URL});
export function LineProvider({children}:{children:ReactNode}){const [settings,setSettings]=useState<LineSettings>({lineId:'',lineUrl:LINE_OA_URL});useEffect(()=>{fetch('/api/settings').then(r=>r.json() as Promise<{settings?:LineSettings}>).then(d=>{if(d.settings)setSettings({...d.settings,lineUrl:LINE_OA_URL})}).catch(()=>{})},[]);return <LineContext.Provider value={settings}>{children}</LineContext.Provider>}
export function LineBooking({service,departure,className='',disabled=false}:{service?:Service;departure?:Departure|null;className?:string;disabled?:boolean}){
const settings=useContext(LineContext),[open,setOpen]=useState(false),[travelDate,setTravelDate]=useState(''),[adults,setAdults]=useState(''),[children,setChildren]=useState('');
const departures=service?.departures||[];
const hasTravelerCount=adults!==''||children!=='';
const totalTravelers=(Number(adults)||0)+(Number(children)||0);
function openForm(){setTravelDate(departure?.start||'');setAdults('');setChildren('');setOpen(true)}
function sendToLine(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const selectedDeparture=service?.departures?.find(d=>d.start===travelDate);const message=[`สวัสดีค่ะ/ครับ ขอบคุณที่สนใจทริป${service?' '+service.title:'กับทัวร์โดนใจ'}`,service?`รหัสทัวร์: ${serviceCode(service)}`:'',travelDate?`วันที่สนใจเดินทาง: ${dateText(travelDate)}${selectedDeparture?' · ราคา '+money(selectedDeparture.price)+' / ท่าน':''}`:'',hasTravelerCount?`ผู้เดินทางรวม ${totalTravelers} คน (ผู้ใหญ่ ${adults||'ไม่ระบุ'} คน, เด็ก ${children||'ไม่ระบุ'} คน)`:'','รบกวนตรวจสอบรอบเดินทางและราคาล่าสุดให้ด้วยค่ะ/ครับ'].filter(Boolean).join('\n');window.location.href=lineLink(settings,message,true)}
return <><div className="contact-actions"><button type="button" disabled={disabled||!!service&&(!service.published||tourClosed(service))||!!departure&&departureExpired(departure)} className={'line-cta '+className} onClick={openForm}><MessageCircle size={20}/>จองเลย</button><a className="phone-cta" href={'tel:'+CONTACT_PHONE} aria-label={'โทร '+CONTACT_PHONE}><Phone size={19}/><span>โทร</span></a></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="request-dialog line-dialog"><DialogTitle>ขอบคุณที่สนใจทริป</DialogTitle><DialogDescription>{service?.title||'ทัวร์โดนใจ'}</DialogDescription><form className="line-booking-form" onSubmit={sendToLine}><label>วันที่สนใจเดินทาง{departures.length?<select value={travelDate} onChange={event=>setTravelDate(event.target.value)}><option value="">ไม่ระบุวันที่</option>{departures.map((d,index)=><option key={`${d.start}-${index}`} value={d.start} disabled={!d.seats||departureExpired(d)}>{dateText(d.start)} – {dateText(d.end)} · {money(d.price)} / ท่าน{departureExpired(d)?' · ปิดรอบแล้ว':!d.seats?' · เต็มหรือรอยืนยันที่นั่ง':''}</option>)}</select>:<input type="date" value={travelDate} onChange={event=>setTravelDate(event.target.value)}/>}</label><div className="form-pair"><label>ผู้ใหญ่ (คน)<input type="number" min="0" max="500" step="1" inputMode="numeric" placeholder="ไม่ระบุ" value={adults} onChange={event=>setAdults(event.target.value)}/></label><label>เด็ก (คน)<input type="number" min="0" max="500" step="1" inputMode="numeric" placeholder="ไม่ระบุ" value={children} onChange={event=>setChildren(event.target.value)}/></label></div><p className="traveler-total">จำนวนผู้เดินทางรวม: <strong>{hasTravelerCount?`${totalTravelers} คน`:'ยังไม่ระบุ'}</strong></p><button type="submit" className="line-cta"><MessageCircle size={20}/>ส่งข้อมูลไป LINE</button><p className="small muted">ไม่จำเป็นต้องกรอกทุกช่อง · LINE จะเปิดข้อความให้ตรวจสอบและกดส่ง</p></form></DialogContent></Dialog></>}
export function LineSettingsEditor(){return <section className="overview-box"><h2>ช่องทางติดต่อบนเว็บไซต์</h2><div className="request-form"><p>ปุ่ม LINE ทุกหน้าเชื่อมกับ LINE OA:</p><a className="line-cta" href={LINE_OA_URL} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>จองเลย</a><code>{LINE_OA_URL}</code><p>ปุ่มโทรศัพท์: <a href={'tel:'+CONTACT_PHONE}>{CONTACT_PHONE}</a></p></div></section>}
