'use client';
import {createContext,useContext,useEffect,useState,ReactNode} from 'react';
import {MessageCircle,Copy,Check,Phone} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {LineSettings,lineLink,LINE_OA_URL,CONTACT_PHONE} from '@/lib/line';
import {Service,money} from '@/lib/catalog';
import {Departure,dateText,serviceCode,departureExpired,tourClosed} from '@/lib/tour';
const LineContext=createContext<LineSettings>({lineId:'',lineUrl:LINE_OA_URL});
export function LineProvider({children}:{children:ReactNode}){const [settings,setSettings]=useState<LineSettings>({lineId:'',lineUrl:LINE_OA_URL});useEffect(()=>{fetch('/api/settings').then(r=>r.json() as Promise<{settings?:LineSettings}>).then(d=>{if(d.settings)setSettings({...d.settings,lineUrl:LINE_OA_URL})}).catch(()=>{})},[]);return <LineContext.Provider value={settings}>{children}</LineContext.Provider>}
export function LineBooking({service,departure,className='',disabled=false}:{service?:Service;departure?:Departure|null;className?:string;disabled?:boolean}){
const settings=useContext(LineContext),[open,setOpen]=useState(false),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(''),[mobile,setMobile]=useState(false);
const message='สวัสดีค่ะ/ครับ สนใจ'+(service?'ทัวร์ '+service.title+'\nรหัส: '+serviceCode(service):'สอบถามและจองทริปกับทัวร์โดนใจ')+(departure?'\nรอบเดินทาง: '+dateText(departure.start)+' – '+dateText(departure.end)+'\nราคาแสดง: '+money(departure.price)+' / ท่าน':'\nขอทราบรอบเดินทางและราคาล่าสุด')+'\nจำนวนผู้เดินทาง: … ท่าน\nรบกวนตรวจสอบที่ว่างและเงื่อนไขการจองให้ด้วยค่ะ/ครับ';
const url=lineLink(settings,message,mobile);
useEffect(()=>setMobile(/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)),[]);
async function copy(){try{await navigator.clipboard.writeText(message);setCopied(true);setCopyError('')}catch{setCopyError('เลือกและคัดลอกข้อความด้านล่างได้เลย')}}
return <><div className="contact-actions"><button type="button" disabled={disabled||!!service&&(!service.published||tourClosed(service))||!!departure&&departureExpired(departure)} className={'line-cta '+className} onClick={()=>{setCopied(false);setOpen(true)}}><MessageCircle size={20}/>จองเลย</button><a className="phone-cta" href={'tel:'+CONTACT_PHONE} aria-label={'โทร '+CONTACT_PHONE}><Phone size={19}/><span>โทร</span></a></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="request-dialog line-dialog"><DialogTitle>จองทริปกับทีมงานผ่าน LINE</DialogTitle><DialogDescription>{service?.title||'ปรึกษาการเดินทางกับทัวร์โดนใจ'}</DialogDescription><div className="line-message"><strong>ข้อความสำหรับส่งให้ทีมงาน</strong><p>{message}</p></div><button className="outline" onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'คัดลอกแล้ว':'คัดลอกข้อความ'}</button>{copyError&&<p className="small">{copyError}</p>}{url?<a className="line-cta" href={url} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>เปิด LINE เพื่อจองทริป</a>:<p className="line-not-connected" role="status">กำลังเตรียมช่องทาง LINE OA สำหรับรับจอง</p>}<p className="small muted">ตรวจข้อความแล้วกดส่งใน LINE เพื่อให้ทีมงานตรวจสอบที่ว่างและยืนยันการจอง</p></DialogContent></Dialog></>}
export function LineSettingsEditor(){return <section className="overview-box"><h2>ช่องทางติดต่อบนเว็บไซต์</h2><div className="request-form"><p>ปุ่ม LINE ทุกหน้าเชื่อมกับ LINE OA:</p><a className="line-cta" href={LINE_OA_URL} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>จองเลย</a><code>{LINE_OA_URL}</code><p>ปุ่มโทรศัพท์: <a href={'tel:'+CONTACT_PHONE}>{CONTACT_PHONE}</a></p></div></section>}
