'use client';
import {createContext,useContext,useEffect,useState,ReactNode} from 'react';
import {MessageCircle,Copy,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {LineSettings,lineLink} from '@/lib/line';
import {Service,money} from '@/lib/catalog';
import {Departure,dateText,serviceCode,departureExpired,tourClosed} from '@/lib/tour';
const LineContext=createContext<LineSettings>({lineId:'',lineUrl:''});
export function LineProvider({children}:{children:ReactNode}){const [settings,setSettings]=useState<LineSettings>({lineId:'',lineUrl:''});useEffect(()=>{fetch('/api/settings').then(r=>r.json() as Promise<{settings?:LineSettings}>).then(d=>{if(d.settings)setSettings(d.settings)}).catch(()=>{})},[]);return <LineContext.Provider value={settings}>{children}</LineContext.Provider>}
export function LineBooking({service,departure,label='จองทริปผ่าน LINE',className='',disabled=false}:{service?:Service;departure?:Departure|null;label?:string;className?:string;disabled?:boolean}){
const settings=useContext(LineContext),[open,setOpen]=useState(false),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(''),[mobile,setMobile]=useState(false);
const message='สวัสดีค่ะ/ครับ สนใจ'+(service?'ทัวร์ '+service.title+'\nรหัส: '+serviceCode(service):'สอบถามและจองทริปกับทัวร์โดนใจ')+(departure?'\nรอบเดินทาง: '+dateText(departure.start)+' – '+dateText(departure.end)+'\nราคาแสดง: '+money(departure.price)+' / ท่าน':'\nขอทราบรอบเดินทางและราคาล่าสุด')+'\nจำนวนผู้เดินทาง: … ท่าน\nรบกวนตรวจสอบที่ว่างและเงื่อนไขการจองให้ด้วยค่ะ/ครับ';
const url=lineLink(settings,message,mobile);
useEffect(()=>setMobile(/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)),[]);
async function copy(){try{await navigator.clipboard.writeText(message);setCopied(true);setCopyError('')}catch{setCopyError('เลือกและคัดลอกข้อความด้านล่างได้เลย')}}
return <><button type="button" disabled={disabled||!!service&&(!service.published||tourClosed(service))||!!departure&&departureExpired(departure)} className={'line-cta '+className} onClick={()=>{setCopied(false);setOpen(true)}}><MessageCircle size={20}/>{label}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="request-dialog line-dialog"><DialogTitle>จองทริปกับทีมงานผ่าน LINE</DialogTitle><DialogDescription>{service?.title||'ปรึกษาการเดินทางกับทัวร์โดนใจ'}</DialogDescription><div className="line-message"><strong>ข้อความสำหรับส่งให้ทีมงาน</strong><p>{message}</p></div><button className="outline" onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'คัดลอกแล้ว':'คัดลอกข้อความ'}</button>{copyError&&<p className="small">{copyError}</p>}{url?<a className="line-cta" href={url} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>เปิด LINE เพื่อจองทริป</a>:<p className="line-not-connected" role="status">กำลังเตรียมช่องทาง LINE OA สำหรับรับจอง</p>}<p className="small muted">ตรวจข้อความแล้วกดส่งใน LINE เพื่อให้ทีมงานตรวจสอบที่ว่างและยืนยันการจอง</p></DialogContent></Dialog></>}
export function LineSettingsEditor(){const [settings,setSettings]=useState<LineSettings>({lineId:'',lineUrl:''}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{fetch('/api/settings').then(r=>r.json() as Promise<{settings?:LineSettings}>).then(d=>{if(d.settings)setSettings(d.settings)}).catch(()=>setNotice('โหลดข้อมูลไม่สำเร็จ'))},[]);async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setNotice('บันทึกแล้ว ปุ่มจองบนเว็บไซต์จะใช้ LINE OA นี้')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}return <section className="overview-box"><h2>LINE OA สำหรับรับจอง</h2><form onSubmit={save} className="request-form"><label>ไอดี LINE OA<input value={settings.lineId} placeholder="@youraccount" onChange={e=>setSettings({...settings,lineId:e.target.value})}/></label><label>ลิงก์เพิ่มเพื่อน LINE OA<input type="url" value={settings.lineUrl} placeholder="https://lin.ee/…" onChange={e=>setSettings({...settings,lineUrl:e.target.value})}/></label><p className="muted small">ใช้ไอดี OA เพื่อเตรียมข้อความชื่อทัวร์และรอบเดินทางบนมือถือ ส่วนลิงก์เพิ่มเพื่อนใช้เปิดบัญชีและรับจองจากคอมพิวเตอร์</p><button className="primary" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกช่องทาง LINE'}</button>{notice&&<p role="status">{notice}</p>}</form></section>}
