import type {Service} from './catalog';
export type TourDay={title:string;description:string;meals:string;hotel:string};
export type Departure={start:string;end:string;price:number;seats:number|null;capacity?:number;commission?:number|null;outboundFlight?:string;returnFlight?:string};
export type WholesaleInfo={supplier:string;sourceFile:string;importedAt:string;notes:string[];meetingTime:string;departureAirport:string;arrivalAirport:string;checkedBaggageKg:number;carryOnKg:number;singleSupplement:number;infantPrice:number;childPolicy:string;deposit:number;balanceDue:string;minimumGroup:number;insuranceCoverage:number;tip:number;tipNotes?:string;hotelNotice:string;taxNotes:string;documents:string;flightNotes:string;imageSources:{caption:string;page?:number;kind?:'pdf'|'ai';url:string}[]};
export type TourFields={wholesale?:WholesaleInfo;serviceCode?:string;activityTags?:string[];closed?:boolean;gallery?:string[];highlights?:string[];itinerary?:TourDay[];departures?:Departure[];included?:string[];excluded?:string[];terms?:string;airline?:string;hotel?:string;pdfUrl?:string;pdfName?:string};
export const japanGallery=['/images/japan.jpg','/images/fuji-lake.jpg','/images/tokyo.jpg','/images/shibuya.jpg','/images/tokyo-neon.jpg','/images/tokyo-tower.jpg','/images/fuji-autumn.jpg','/images/temple-evening.jpg'];
export const imageChoices=[...japanGallery,'/images/europe.jpg'];
export function validImage(v:unknown):v is string {if(typeof v!=='string')return false;if(imageChoices.includes(v)||/^\/api\/media\/[a-f0-9-]+\.(jpg|png|webp)$/.test(v))return true;try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&v.length<2000;}catch{return false}}
function endDate(start:string,days:number){const d=new Date(start+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days-1);return d.toISOString().slice(0,10)}
export function coverGallery(s:Pick<Service,'image'|'gallery'>){return [...new Set([s.image,...(s.gallery||[])].filter(Boolean))].slice(0,30)}
export function tourDefaults(s:Service):Service {s={...s,gallery:coverGallery({...s,gallery:s.gallery||(s.category==='ทัวร์'?(s.country==='ญี่ปุ่น'?japanGallery:['/images/europe.jpg']):[s.image])})};if(s.category!=='ทัวร์')return {...s,image:s.gallery?.[0]||s.image,gallery:s.gallery||[s.image]};const japan=s.country==='ญี่ปุ่น';const days=s.id==='japan'?5:s.id==='japan-private'?6:s.id==='europe'?9:7;const routes=japan?['กรุงเทพฯ — เดินทางสู่ญี่ปุ่น','โตเกียว — วัดอาซากุสะ — ย่านเมืองเก่า','ภูเขาไฟฟูจิ — ทะเลสาบคาวากุจิโกะ','โตเกียว — ช้อปปิ้งและเดินเที่ยวตามอัธยาศัย']:['กรุงเทพฯ — เดินทางสู่ออสเตรีย','เวียนนา — ชมเมืองเก่า','ฮัลล์ชตัทท์ — หมู่บ้านริมทะเลสาบ','เส้นทางธรรมชาติ — ชมเทือกเขาแอลป์'];return {...s,image:s.gallery?.[0]||s.image,serviceCode:s.serviceCode||s.id.toUpperCase(),activityTags:s.activityTags||(japan?['ชมฟูจิ','ช้อปปิ้ง']:['ธรรมชาติ','เมืองเก่า']),gallery:s.gallery|| (japan?japanGallery:['/images/europe.jpg']),highlights:s.highlights|| (japan?['ชมวิวภูเขาไฟฟูจิและทะเลสาบคาวากุจิโกะ','เดินชมวัดอาซากุสะและย่านเมืองเก่า','มีเวลาเดินเที่ยวและเลือกซื้อของในโตเกียว']:['ชมหมู่บ้านฮัลล์ชตัทท์ริมทะเลสาบ','สัมผัสบรรยากาศเมืองเก่าและธรรมชาติแอลป์']),itinerary:s.itinerary||Array.from({length:days},(_,i)=>({title:i===days-1?(japan?'ญี่ปุ่น — เดินทางกลับกรุงเทพฯ':'ออสเตรีย — เดินทางกลับกรุงเทพฯ'):routes[i%routes.length],description:i===days-1?'เตรียมสัมภาระและเดินทางสู่สนามบินเพื่อกลับกรุงเทพฯ':i===0?'พบทีมงานที่สนามบิน ตรวจเอกสารและสัมภาระก่อนออกเดินทาง':'เดินทางชมสถานที่ตามเส้นทางที่กำหนด มีเวลาถ่ายภาพและพักผ่อน โดยลำดับสถานที่อาจปรับตามสภาพอากาศและการเดินทาง',meals:i===0||i===days-1?'ตามบริการบนเที่ยวบิน':'เช้า / กลางวัน / เย็น',hotel:i===0||i===days-1?'ตามตารางเที่ยวบิน':japan?'โรงแรมระดับ 3–4 ดาว (รอยืนยัน)':'โรงแรมระดับ 4 ดาว (รอยืนยัน)'})),departures:s.departures||[{start:'2026-11-12',end:`2026-11-${12+days-1}`,price:s.price,seats:20,capacity:20,commission:0},{start:'2026-12-03',end:`2026-12-${String(3+days-1).padStart(2,'0')}`,price:s.price+2000,seats:12,capacity:20,commission:0},{start:'2026-12-24',end:endDate('2026-12-24',days),price:s.price+5000,seats:0,capacity:20,commission:0}],included:s.included||['ค่าที่พักตามโปรแกรม','รถรับส่งและการเดินทางตามรายการ','อาหารตามที่ระบุในโปรแกรม','ทีมงานดูแลตลอดเส้นทาง'],excluded:s.excluded||['ค่าใช้จ่ายส่วนตัวและบริการนอกโปรแกรม','ค่าธรรมเนียมวีซ่า (ถ้ามี)','ค่าทิปและค่าใช้จ่ายอื่นตามใบเสนอราคา'],terms:s.terms||'โปรแกรม รอบเดินทาง จำนวนที่นั่ง และราคาเป็นข้อมูลตัวอย่าง ต้องให้ทีมงานยืนยันก่อนจอง เงื่อนไขชำระเงิน การเปลี่ยนแปลง และยกเลิกจะระบุในใบเสนอราคา',airline:s.airline||'ยืนยันสายการบินในใบเสนอราคา',hotel:s.hotel||'โรงแรมระดับ 3–4 ดาว (รอยืนยัน)'};}
export function dateText(d:string){return new Date(d+'T12:00:00').toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'2-digit'})}

// Evaluate against the site business date on every read; no background job is required.
export function businessDate(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Baku',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
export function departureExpired(d:Departure,today=businessDate()){return !!d.start&&d.start<today}
export function tourClosed(s:Service,today=businessDate()){return s.category==='ทัวร์'&&!!s.departures?.length&&s.departures.every(d=>departureExpired(d,today))}
export function serviceCode(s:Service){return s.serviceCode||s.id.toUpperCase()}
function slugCountry(country:string){const english:Record<string,string>={'ไต้หวัน':'taiwan','ตุรเคีย':'turkey','สหรัฐอเมริกา':'usa'};return english[country]||country.normalize('NFC').trim().replace(/\s+/g,'-').replace(/[^\p{L}\p{M}\p{N}-]/gu,'').toLowerCase()}
export function serviceSlug(s:Service){return `${slugCountry(s.country)}-${serviceCode(s)}`.normalize('NFC').trim().replace(/\s+/g,'-').replace(/[^\p{L}\p{M}\p{N}-]/gu,'').toLowerCase()}
export function legacyServiceSlug(s:Service){return `${s.country}-${serviceCode(s)}`.normalize('NFC').trim().replace(/\s+/g,'-').replace(/[^\p{L}\p{M}\p{N}-]/gu,'').toLowerCase()}
export function activeDepartures(s:Service,today=businessDate()){return (s.departures||[]).filter(d=>!departureExpired(d,today)).sort((a,b)=>a.start.localeCompare(b.start))}
export function startingPrice(s:Service){const ds=activeDepartures(s);return ds.length?Math.min(...ds.map(d=>d.price)):s.price}

export function validDate(v:unknown):v is string {if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T12:00:00Z');return !isNaN(d.getTime())&&d.toISOString().slice(0,10)===v}
